# Generated by Django 2.1.5 on 2019-04-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElemedbDelivery',
            fields=[
                ('deliverycode', models.CharField(db_column='deliveryCode', max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'elemedb_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbDeliveryperson',
            fields=[
                ('deliverypcode', models.CharField(db_column='deliveryPCode', max_length=15, primary_key=True, serialize=False)),
                ('deliverypname', models.CharField(db_column='deliveryPName', max_length=24)),
                ('deliverypphone', models.CharField(db_column='deliveryPPhone', max_length=11)),
            ],
            options={
                'db_table': 'elemedb_deliveryPerson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbRstrt',
            fields=[
                ('rstrtname', models.CharField(db_column='rstrtName', max_length=24, primary_key=True, serialize=False)),
                ('rstrtclass', models.CharField(db_column='rstrtClass', max_length=15)),
                ('rstrtaddr', models.CharField(db_column='rstrtAddr', max_length=96)),
                ('rstrtphone', models.CharField(db_column='rstrtPhone', max_length=15)),
                ('wrkinhrsfrom', models.TimeField(db_column='wrkinHrsFrom')),
                ('wrkinhrsto', models.TimeField(db_column='wrkinHrsTo')),
            ],
            options={
                'db_table': 'elemedb_rstrt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbRstrtmenu',
            fields=[
                ('dishcode', models.CharField(db_column='dishCode', max_length=15, primary_key=True, serialize=False)),
                ('dishname', models.CharField(db_column='dishName', max_length=20)),
                ('dishprice', models.FloatField(db_column='dishPrice')),
                ('dishsaleamount', models.IntegerField(db_column='dishSaleAmount')),
            ],
            options={
                'db_table': 'elemedb_rstrtMenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbUser',
            fields=[
                ('username', models.CharField(db_column='userName', max_length=24, primary_key=True, serialize=False)),
                ('userphone', models.CharField(db_column='userPhone', max_length=11)),
                ('logincode', models.CharField(db_column='loginCode', max_length=16)),
                ('paycode', models.CharField(db_column='payCode', max_length=6)),
            ],
            options={
                'db_table': 'elemedb_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbUseraddr',
            fields=[
                ('addresscode', models.IntegerField(db_column='addressCode', primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=24)),
                ('gender', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=96)),
                ('tag', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'elemedb_userAddr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbUserfav',
            fields=[
                ('favID', models.IntegerField(db_column='favID', primary_key=True, serialize=False)),
                ('deliveryleast', models.IntegerField(db_column='deliveryLeast')),
                ('distance', models.FloatField()),
                ('leasttime', models.IntegerField(db_column='leastTime')),
            ],
            options={
                'db_table': 'elemedb_userFav',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElemedbUserorder',
            fields=[
                ('ordercode', models.CharField(db_column='orderCode', max_length=20, primary_key=True, serialize=False)),
                ('pay', models.FloatField()),
                ('ordertime', models.DateTimeField(db_column='orderTime')),
            ],
            options={
                'db_table': 'elemedb_userOrder',
                'managed': False,
            },
        ),
    ]
